### ISSUE TITLE
could not run app.py

### ISSUE THREAD

**Issue by dustyraven** [fedecarg/webpy-mvc#2]
exact following the instructions gives:

$ python app.py

Traceback (most recent call last):
  File "app.py", line 8, in <module>
    app = mvc.application(routes.urls, {}, autoreload=True)
AttributeError: 'module' object has no attribute 'application'

**Comment by dustyraven** [comment]
after following new download/install instructions, situation seems the same:

dusty@dusty:~/dtmp/webpy-mvc-master/src$ python app.py 
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    app = mvc.application(routes.urls, {}, autoreload=True)
AttributeError: 'module' object has no attribute 'application'
